### ISSUE TITLE
Back button ?

### ISSUE THREAD

**Issue by agenceKanvas** [briangonzalez/codrops-medium-style-page-transitions#4]
Any tips to add a back button ? Tried some things but didn't get it to work.
Any advice would be great ! Thanks a lot, and great tutorial !

**Comment by briangonzalez** [comment]
@KuneStudio Thanks! Here's how you'd want to do it.

**HTML**

First, create a button on your html.

``` html
<button class='back'>Go Back</button>
```

**JAVASCRIPT**

Then bind an event list to it, which tells the HTML5 history object to go "back".

``` javascript
$('button.back').on('click', function(){
  history.back()
})
```
